"""notification related object nullable

Revision ID: 595c3bb9a4fb
Revises: 289d4a9d3797
Create Date: 2025-04-12 19:14:13.558205

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "595c3bb9a4fb"
down_revision: str | None = "289d4a9d3797"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("notifications", "related_object_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("notifications", "related_object_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
