"""comment threads

Revision ID: 7d7dd79f4cc4
Revises: c659474cfeec
Create Date: 2025-04-13 13:00:43.009283

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d7dd79f4cc4"
down_revision: str | None = "c659474cfeec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("publication_comments", sa.Column("parent_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "publication_comments_parent_id_fkey",
        "publication_comments",
        "publication_comments",
        ["parent_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("publication_comments_parent_id_fkey", "publication_comments", type_="foreignkey")
    op.drop_column("publication_comments", "parent_id")
    # ### end Alembic commands ###
