"""user notifications

Revision ID: d85c958c9901
Revises: 008746c3816d
Create Date: 2025-04-12 18:06:30.406312

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import open_gallery.persistence.type_decorators

# revision identifiers, used by Alembic.
revision: str = "d85c958c9901"
down_revision: str | None = "008746c3816d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("publication_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "subject",
            open_gallery.persistence.type_decorators.notifications.NotificationTypeTypeImpl(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            open_gallery.persistence.type_decorators.datetime.UTCDateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            open_gallery.persistence.type_decorators.datetime.UTCDateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["publication_id"], ["publications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notifications")
    # ### end Alembic commands ###
