"""notification type

Revision ID: 4ce61c9cd010
Revises: d85c958c9901
Create Date: 2025-04-12 18:20:31.151467

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import open_gallery.persistence.type_decorators

# revision identifiers, used by Alembic.
revision: str = "4ce61c9cd010"
down_revision: str | None = "d85c958c9901"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications",
        sa.Column(
            "type",
            open_gallery.persistence.type_decorators.notifications.NotificationTypeTypeImpl(),
            nullable=False,
        ),
    )
    op.drop_column("notifications", "subject")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notifications", sa.Column("subject", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column("notifications", "type")
    # ### end Alembic commands ###
