"""publication references

Revision ID: c659474cfeec
Revises: e0791884b7af
Create Date: 2025-04-13 12:04:31.307850

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c659474cfeec"
down_revision: str | None = "e0791884b7af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "publication_references",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["publications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["publications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("source_id", "target_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("publication_references")
    # ### end Alembic commands ###
