"""notification seen

Revision ID: e0791884b7af
Revises: 595c3bb9a4fb
Create Date: 2025-04-12 19:16:23.717931

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0791884b7af"
down_revision: str | None = "595c3bb9a4fb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notifications", sa.Column("seen", sa.Boolean(), server_default=sa.text("'false'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notifications", "seen")
    # ### end Alembic commands ###
